apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-sleep-container-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: stage
            namespace: sleeper-stage
          - env: prod
            namespace: sleeper-prod
          - env: dev
            namespace: sleeper-dev
  template:
    metadata:
      name: 'sleep-container-{{.env}}'
      labels:
        kargo.akuity.io/env: '{{.env}}'
      annotations:
        # lets Kargo manage/promote this Application as part of a Stage
        kargo.akuity.io/authorized-stage: 'kargo-demo:{{.env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/martysohio/kargo-demo.git
        targetRevision: main
        path: sleeper-app/charts/sleep-container
        helm:
          releaseName: 'sleep-container-{{.env}}'
          valueFiles:
            - 'sleeper-app/{{.env}}/values.yaml'
          parameters:
            - name: replicaCount
              value: '{{.replicaCount}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true