apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
namespace: stage-kargo-fastapi
namePrefix: stage-
images:
- name: ghcr.io/martysohio/fastapi-app
  newTag: 1.1.5
