apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
namespace: prod-kargo-fastapi
namePrefix: prod-
images:
- name: ghcr.io/martysohio/fastapi-app
  newTag: 1.0.2
