apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: kargo-fastapi
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/martysohio/kargo-demo.git
    targetRevision: main
    path: kargo-fastapi

  destination:
    server: http://cluster-kargo-demo:8001

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true