apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  # - kargo/project.yaml
  # - kargo/warehouse.yaml
  # - kargo/stage-dev.yaml
  # - kargo/stage-stage.yaml
  # - kargo/stage-prod.yaml
  # - kargo/promotion-template.yaml