apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  promotionPolicies:
  - stageSelector:
      name: dev
    autoPromotionEnabled: true
  - stageSelector:
      name: stage
    autoPromotionEnabled: true