apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: fastapi
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitopsRepo
        value: https://github.com/${GITHUB_USER}/${GITHUB_REPO}
      - name: imageRepo
        value: ghcr.io/${GITHUB_USER}/guestbook
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitopsRepo }}
          checkout:
          - branch: main
            path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./out/app/env/dev
          images:
          - image: ${{ vars.imageRepo }}
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out