apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: fastapi
  namespace: kargo-demo

spec:
  subscriptions:
    - image:
        repoURL: ghcr.io/martysohio/fastapi-app
    - git:
        repoURL: https://github.com/martysohio/kargo-demo.git
        commitSelectionStrategy: NewestFromBranch
        branch: main
        includePaths:
          - sleeper-app/charts/sleep-container